name: Build and Push Ventas to ECR

on:
  push:
    branches:
      - deploy
    paths:
      - 'backend/Springboot-API-REST-VENTAS/**'
      - '.github/workflows/back-ventas-deployment.yaml'

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPO_DB_VENTAS: ${{ vars.ECR_REPO_DB_VENTAS }}
  ECR_REPO_VENTAS: ${{ vars.ECR_REPO_VENTAS }}
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Necesario en cuentas de laboratorio de AWS (ej. AWS Academy)
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull and Tag Docker image - DB Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker pull postgres:15-alpine
          docker tag postgres:15-alpine $ECR_REGISTRY/$ECR_REPO_DB_VENTAS:$IMAGE_TAG

      - name: Build Docker image - Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker build -t $ECR_REGISTRY/$ECR_REPO_VENTAS:$IMAGE_TAG ./backend/Springboot-API-REST-VENTAS

      - name: Push Docker image - DB Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker push $ECR_REGISTRY/$ECR_REPO_DB_VENTAS:$IMAGE_TAG

      - name: Push Docker image - Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker push $ECR_REGISTRY/$ECR_REPO_VENTAS:$IMAGE_TAG
